### PR TITLE
Reorganize solution file

### PR DESCRIPTION
**Pull request by YoakeArsene**
@orienthoanguyen

### CODE REVIEW

**Comment by orienthoanguyen** [comment]
Hey @YoakeArsene , why did you remove git ignore files?

**Comment by orienthoanguyen** [comment]
image
And I can't open FPTBook folder?

**Comment by YoakeArsene** [comment]
image

**Comment by YoakeArsene** [comment]
I merge the remote repo containing the web pj file then remove it and add the whole reorganized solution file (including web pj file and unit test pj file)

**Comment by orienthoanguyen** [comment]
ok let's merge this change and see

**Review by orienthoanguyen — APPROVED** [review]

**Pull request merged**
